spring:
 application:
  name: the_system_of_student_information
 datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:5432}/
  username: postgres
  password: "1234"
 jpa:
  show-sql: true
  generate-ddl: true
  hibernate:
   ddl-auto: validate
  database: postgresql
 liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yml